# Generated by Django 5.1.7 on 2025-03-21 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diseases', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_of_disease', models.CharField(max_length=100)),
                ('diagnosis_methods', models.TextField()),
                ('complications', models.TextField()),
                ('epidemiology', models.TextField()),
                ('prognosis', models.TextField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.disease')),
            ],
        ),
    ]
