# Generated by Django 5.2.1 on 2025-06-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('symptoms', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientcase')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.symptom')),
            ],
            options={
                'unique_together': {('patient', 'symptom')},
            },
        ),
    ]
