# Generated by Django 5.2.1 on 2025-06-23 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ontology_description', models.TextField(blank=True, null=True)),
                ('uniprot_description', models.TextField(blank=True, null=True)),
                ('mondo_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('icd_10_code', models.CharField(blank=True, max_length=20, null=True)),
                ('icd_11_code', models.CharField(blank=True, max_length=20, null=True)),
                ('protein_count', models.PositiveIntegerField(default=0)),
                ('direct_association_count', models.PositiveIntegerField(default=0)),
                ('is_rare', models.BooleanField(default=False)),
                ('is_chronic', models.BooleanField(default=False)),
                ('is_hereditary', models.BooleanField(default=False)),
                ('is_contagious', models.BooleanField(default=False)),
                ('severity_level', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical'), ('variable', 'Variable')], default='moderate', max_length=20)),
                ('typical_age_onset', models.CharField(choices=[('infancy', 'Infancy'), ('childhood', 'Childhood'), ('adolescence', 'Adolescence'), ('adult', 'Adult'), ('middle_age', 'Middle Age'), ('elderly', 'Elderly'), ('any_age', 'Any Age')], default='any_age', max_length=20)),
                ('gender_prevalence', models.CharField(choices=[('male', 'More Common in Males'), ('female', 'More Common in Females'), ('equal', 'Equal Prevalence')], default='equal', max_length=20)),
                ('diagnostic_confidence_threshold', models.FloatField(default=0.7, help_text='Minimum AI confidence to recommend this disease', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='diseases_di_name_f1e1dd_idx'), models.Index(fields=['is_chronic', 'is_rare'], name='diseases_di_is_chro_d188e1_idx'), models.Index(fields=['severity_level'], name='diseases_di_severit_fafc41_idx')],
            },
        ),
    ]
