# Generated by Django 5.1.7 on 2025-03-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('disease_ontology_description', models.TextField()),
                ('uniprot', models.CharField(max_length=255)),
                ('uniprot_description', models.TextField()),
                ('mondo_id', models.CharField(max_length=100)),
                ('disease_data_source', models.CharField(max_length=255)),
                ('associated_disease', models.CharField(blank=True, max_length=255, null=True)),
                ('protein_count', models.PositiveIntegerField(blank=True, null=True)),
                ('direct_association_count', models.PositiveIntegerField(blank=True, null=True)),
                ('gard_rare', models.BooleanField(default=False)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_ontology_url', models.URLField(blank=True, null=True)),
                ('mondosource_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
