# Generated by Django 5.1.7 on 2025-03-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentsPrevention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_1', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment_2', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment_3', models.CharField(blank=True, max_length=255, null=True)),
                ('prevention_1', models.CharField(blank=True, max_length=255, null=True)),
                ('prevention_2', models.CharField(blank=True, max_length=255, null=True)),
                ('prevention_3', models.CharField(blank=True, max_length=255, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.disease')),
            ],
        ),
    ]
