# Generated by Django 5.2.1 on 2025-06-23 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_alter_diseasesymptom_frequency_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasesymptom',
            name='frequency_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='diseasesymptom',
            name='specificity_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
