# Generated by Django 5.2.1 on 2025-06-23 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0002_initial'),
        ('diseases', '__first__'),
        ('patient', '0001_initial'),
        ('patientsymptoms', '0001_initial'),
        ('symptoms', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcase',
            name='reported_symptoms',
            field=models.ManyToManyField(through='patientsymptoms.PatientSymptom', to='symptoms.symptom'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='suggested_diseases',
            field=models.ManyToManyField(through='diagnosis.AIDiagnosis', to='diseases.disease'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
