# Generated by Django 5.2.1 on 2025-06-23 12:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diseases', '0001_initial'),
        ('patient', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('explanation', models.TextField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='diseases.disease')),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='patient.patientcase')),
            ],
            options={
                'ordering': ['patient_case', 'rank'],
                'unique_together': {('patient_case', 'disease')},
            },
        ),
    ]
