# Generated by Django 5.2.1 on 2025-06-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidiagnosis',
            name='patient_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='patient.patientcase'),
        ),
        migrations.AlterUniqueTogether(
            name='aidiagnosis',
            unique_together={('patient_case', 'disease')},
        ),
    ]
